# Generated by Django 2.0.6 on 2018-09-11 18:41

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Designation', models.CharField(default='', max_length=25)),
                ('MobileNumber', phone_field.models.PhoneField(default='', max_length=31)),
                ('MailID', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
