# Generated by Django 2.0.6 on 2018-10-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='Designation',
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='Merchant',
            field=models.CharField(default='', max_length=25),
        ),
    ]
