# Generated by Django 2.0.6 on 2018-10-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20181002_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmodel',
            old_name='Merchant',
            new_name='Designation',
        ),
    ]
