# Generated by Django 2.0.6 on 2018-10-02 17:07

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('News', models.CharField(default='', max_length=1000)),
                ('MobileNumber', phone_field.models.PhoneField(default='', max_length=31)),
                ('MailID', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='StaffModel',
        ),
    ]
