# Generated by Django 2.0.6 on 2018-09-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society_creategroupmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofgroup', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('mailid', models.CharField(default='', max_length=100)),
                ('adminofgroup', models.BooleanField(default=True)),
                ('groupaprrovedbybuildingadmin', models.BooleanField(default=False)),
                ('restrictedtomybuilding', models.BooleanField(default=True)),
            ],
        ),
    ]
