# Generated by Django 2.0.6 on 2018-09-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_auto_20180930_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society_memberaddmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='', max_length=100)),
                ('mailid', models.EmailField(default='', max_length=254)),
                ('chat', models.CharField(default='', max_length=200)),
                ('approvedbygroupadmin', models.BooleanField(default=False)),
            ],
        ),
    ]
