# Generated by Django 2.0.6 on 2018-09-30 19:38

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_society_memberaddmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='society_memberaddmodel',
            name='mobileNo',
            field=phone_field.models.PhoneField(default='', max_length=31),
        ),
    ]
