# Generated by Django 2.0.6 on 2018-09-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_society_memberaddmodel_mobileno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society_memberaddmodel',
            name='mobileNo',
        ),
    ]
