# Generated by Django 2.0.6 on 2018-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0005_remove_society_memberaddmodel_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_memberaddmodel',
            name='chat',
            field=models.CharField(default='New request', max_length=200),
        ),
    ]
