# Generated by Django 2.0.6 on 2018-09-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0008_auto_20181001_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_memberaddmodel',
            name='mailid',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
