# Generated by Django 2.0.5 on 2018-06-09 13:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsExpense', models.BooleanField(default=False)),
                ('user', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanker_water_charges', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('Security_Payment', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('STP_Payment', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('Water_Dept_Payment', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('Opening_Balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('Maintenance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='Type_of_Description',
            field=models.ManyToManyField(to='accounts.Description'),
        ),
    ]
