# Generated by Django 2.0.5 on 2018-06-09 16:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='Maintenance',
        ),
        migrations.RemoveField(
            model_name='description',
            name='Opening_Balance',
        ),
        migrations.RemoveField(
            model_name='description',
            name='STP_Payment',
        ),
        migrations.RemoveField(
            model_name='description',
            name='Security_Payment',
        ),
        migrations.RemoveField(
            model_name='description',
            name='Tanker_water_charges',
        ),
        migrations.RemoveField(
            model_name='description',
            name='Water_Dept_Payment',
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='Amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='description',
            name='Fields',
            field=models.CharField(default='', max_length=100),
        ),
    ]
