# Generated by Django 2.0.5 on 2018-06-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180609_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsmodel',
            old_name='Type_of_Description',
            new_name='Type',
        ),
    ]
