# Generated by Django 2.0.5 on 2018-06-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180609_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsmodel',
            name='Type',
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='Type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
