# Generated by Django 2.0.6 on 2018-08-08 15:44

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180609_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20)),
                ('Year', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20)),
                ('buildingName', models.CharField(default='', max_length=255)),
                ('UserId', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='buildingName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='expenseApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='houseNo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='unitNo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
