# Generated by Django 2.0.6 on 2018-09-05 18:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180808_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=20),
        ),
    ]
