# Generated by Django 2.0.6 on 2018-09-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180905_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferenceModel',
        ),
    ]
