# Generated by Django 2.0.5 on 2018-05-26 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Typeofvisit', models.CharField(default='', max_length=25)),
                ('Unit', models.CharField(default='', max_length=25)),
                ('Mobile_Num', phone_field.models.PhoneField(default='', max_length=31)),
                ('Visitor_MailID', models.EmailField(default='', max_length=254)),
                ('Name', models.CharField(default='', max_length=100)),
                ('Reference', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
