# Generated by Django 2.0.5 on 2018-05-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20180526_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityoffice',
            old_name='PersonMeeting',
            new_name='user',
        ),
    ]
