# Generated by Django 2.0.5 on 2018-05-26 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20180526_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityoffice',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
