# Generated by Django 2.0.5 on 2018-06-11 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_auto_20180527_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityoffice',
            name='Datetime',
        ),
        migrations.AddField(
            model_name='securityoffice',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='securityoffice',
            name='Time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
