# Generated by Django 2.0.5 on 2018-06-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_auto_20180612_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityoffice',
            name='Date',
        ),
    ]
