# Generated by Django 2.0.5 on 2018-06-11 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_remove_securityoffice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityoffice',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
