# Generated by Django 2.0.5 on 2018-06-11 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_securityoffice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityoffice',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='securityoffice',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2018, 6, 11, 19, 26, 34, 780484, tzinfo=utc)),
        ),
    ]
