# Generated by Django 2.0.5 on 2018-06-11 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_auto_20180612_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityoffice',
            name='Time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
