# Generated by Django 2.0.6 on 2018-08-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_auto_20180612_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityoffice',
            name='BuildingName',
            field=models.CharField(default='', max_length=25),
        ),
    ]
