# Generated by Django 2.0.6 on 2018-08-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_securityoffice_buildingname'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityoffice',
            name='houseNo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
