# Generated by Django 2.0.5 on 2018-07-03 14:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_resetpasswordtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.BigIntegerField(default='')),
                ('date_time', models.DateTimeField(default=datetime.date.today)),
                ('user_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='resetpasswordtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResetPasswordToken',
        ),
    ]
