# Generated by Django 2.0.6 on 2018-08-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0007_auto_20180703_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='houseNo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
