# Generated by Django 2.1 on 2018-08-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=1000)),
                ('IssueResolved', models.BooleanField(default=False)),
                ('Feedback', models.CharField(max_length=255)),
                ('Created', models.DateTimeField(auto_now=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('UserID', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TicketList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WaterIssues', models.CharField(max_length=255)),
                ('ElectricityIssues', models.CharField(max_length=1000)),
                ('BuildingIssues', models.BooleanField(default=False)),
                ('SecurityIssues', models.CharField(max_length=255)),
                ('BookingIssues', models.DateTimeField(auto_now=True)),
                ('Others', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
