# Generated by Django 2.1 on 2018-08-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_ticketsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdescription',
            name='BuildingName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ticketdescription',
            name='TicketID',
            field=models.IntegerField(default='1'),
        ),
    ]
