# Generated by Django 2.1 on 2018-08-30 19:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20180830_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdescription',
            name='BuildingName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ticketdescription',
            name='TicketID',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20),
        ),
    ]
