# Generated by Django 2.1 on 2018-08-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_ticketdescription_ticketlist_ticketsname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdescription',
            name='Feedback',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketdescription',
            name='IssueResolved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
